version: '3.3'

services:

  mongo:
    image: mongo:5.0.3
    ports:
      - 12017:27017
    environment:
      MONGO_INTITD_ROOT_USERNAME: development
      MONGO_INITDB_ROOT_PASSWORD: messwithbestdieliketherest
    
  mongo-express:
    image: mongo:5.0.3
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGO_INTITD_ROOT_USERNAME: development
      ME_MONGO_INITD_ROOT_USERNAME: development
      ME_CONFIG_MONGODB_URL: mongodb://development:messwithbestdieliketherest@mongo:27017/